[package]
name = "hexafreeze"
version = "0.1.0"
edition = "2021"
authors = ["Blocklisted <blocklisted@pm.me>"]
readme = "README.md"
repositry = "https://github.com/blocklisted/hexafreeze"
license = "MIT"
keywords = ["async", "web", "distributed", "snowflake", "unique"]
categories = ["web-programming", "database"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
log = "0.4"
tokio = {version = "1.23", features = ["sync"]}

[dev-dependencies]
dashmap = "5.4.0"
num_cpus = "1.1"
env_logger = "0.10"